import random
import tkinter as tk
from tkinter import ttk
from tkinter import messagebox

def generate_excuse():
    excuses = [
        "You have such a unique fashion sense. It's... bold.",
        "Wow, you're actually on time for once. Miracles do happen.",
        "You really know how to make a statement, even if it's usually the wrong one.",
        "I admire your confidence to wear something like that in public.",
        "Your attention to detail is... impressive, considering how little you actually care.",
        "Congratulations! You managed to accomplish the bare minimum. I'm so proud.",
        "I never cease to be amazed at how you can turn the simplest task into a complicated one.",
        "Your opinion is... interesting. I'll pretend to consider it.",
        "You're like a dictionary of bad ideas. It's quite impressive.",
        "You have a remarkable talent for asking pointless questions.",
        "Your work ethic is truly one of a kind. In a bad way, of course.",
        "Your outfit screams, 'I don't care,' but in a fashionable way, I suppose.",
        "You're the master of making the easiest tasks seem challenging. It's a gift, really.",
        "You have an incredible ability to turn any conversation into an argument. It's impressive, in a frustrating way.",
        "Your sense of humor is... unique. Not everyone gets it, but that's probably a good thing.",
        "You always find a way to stand out, even in a room full of people who don't want you there.",
        "Your ideas are like shooting stars: they flash by quickly and then disappear forever.",
        "You have an uncanny knack for saying the wrong thing at the worst possible time.",
        "Your lack of attention to detail is truly awe-inspiring.",
        "You're really good at pretending to listen. I almost believed you for a second.",
        "I love how you confidently speak on topics you know nothing about. It's truly remarkable.",
        "You really have a talent for making things more complicated than they need to be.",
        "You're like a breath of fresh air... for people who find the smell of rotting garbage refreshing.",
        "You're so good at making excuses, you should teach a masterclass.",
        "Your creativity knows no bounds when it comes to avoiding actual work.",
        "You have a special talent for making the simplest tasks seem like rocket science.",
        "You're a true expert at finding ways to avoid responsibility.",
        "You're the Picasso of procrastination. Your masterpiece is never getting things done.",
        "Your ability to misunderstand even the clearest instructions is truly impressive.",
        "You're like a human bulldozer, plowing through conversations and leaving destruction in your wake.",
        "You're the gold medalist of turning compliments into insults. It's truly a talent.",
        "You have an incredible ability to make everything about you. It's like a superpower, but annoying.",
        "I envy your ability to effortlessly turn small tasks into huge projects.",
        "You're the shining example of what not to do. Thanks for the constant reminder.",
        "Your work is so consistently average that it's almost impressive.",
        "You're like a walking, talking dictionary of bad decisions.",
        "Your outfit choices are always... interesting. I never know what to expect.",
        "You have a real talent for making people feel uncomfortable. It's like second nature to you.",
        "You always find a way to make yourself the center of attention, even when nobody wants you to be.",
        "You're the master of making simple tasks last forever. It's truly remarkable.",
        "You're so good at multitasking: doing nothing while appearing busy.",
        "You have a real talent for stating the obvious. It's a rare gift.",
        "Your ability to take criticism is... nonexistent.",
        "You're a true artist when it comes to dodging responsibility.",
        "Your decision-making skills are truly unparalleled. And by that, I mean consistently terrible.",
        "I'm always in awe of your impeccable timing to show up when nobody wants you around.",
        "You're like a black hole of productivity, sucking everything in and producing nothing.",
        "Your unique perspective on life never fails to leave me speechless. And not in a good way.",
        "You have an uncanny talent for turning compliments into awkward moments. It's truly a skill.",
        "You really know how to make an entrance... and an exit. Mostly the exit part.",
        "Your ability to overcomplicate the simplest tasks is truly astounding.",
        "You're a real pro at making people feel inferior without even trying.",
        "Your complete lack of self-awareness is truly a sight to behold.",
        "You're like a walking, talking cautionary tale. Thanks for reminding us what not to do.",
        "You're the undisputed champion of finding ways to waste time. It's impressive, really.",
        "Your confidence is truly inspiring... to people who don't know you.",
        "You always manage to find a way to make everything about yourself. It's a rare talent.",
        "You're a true magician when it comes to disappearing just when we need you.",
        "Your attention to detail is truly unmatched, especially when it comes to finding faults in others.",
        "You're so good at pretending to care, it's almost convincing. Almost.",
        "You have an incredible ability to make everything about you, even when it has nothing to do with you.",
        "You're a master of finding the most inefficient way to get things done. It's truly remarkable.",
        "Your ability to misunderstand even the simplest instructions is truly mind-boggling.",
        "You always manage to make the simplest tasks seem like rocket science. It's quite a talent.",
        "You're the reigning champion of missing the point. Congratulations on the impressive streak.",
        "Your dedication to doing the bare minimum is truly admirable.",
        "You really have a gift for finding faults in everything. It's like a superpower, but annoying.",
        "Your fashion choices are... bold, to say the least. Not everyone can pull off such unique looks.",
        "You're like a superhero, always appearing when nobody needs you.",
        "Your ability to turn any situation into a disaster is truly unmatched.",
        "You're the real MVP of making mountains out of molehills. It's quite a talent.",
        "Your communication skills are truly exceptional... exceptionally bad.",
        "You have an uncanny talent for making things unnecessarily complicated.",
        "You always manage to bring a unique level of chaos wherever you go. It's quite impressive.",
        "You're like a master of miscommunication. It's truly an art form.",
        "Your ability to avoid accountability is truly a marvel.",
        "You have an amazing talent for turning compliments into awkward moments. It's quite impressive.",
        "You really know how to make an impression... even if it's usually a negative one.",
        "You're the Picasso of overthinking. Your masterpieces are always a mess.",
        "Your presence is truly a gift... that keeps on giving frustration.",
        "You're a real pro at finding ways to complicate the simplest tasks. It's quite a skill.",
        "You have a remarkable talent for turning compliments into backhanded insults. It's truly a gift.",
        "You're like a walking, talking paradox. It's truly fascinating.",
        "Your decision-making skills are truly remarkable... in their inconsistency.",
        "You're like a human magnet for drama. It's truly impressive.",
        "Your ability to find faults in everything is truly unmatched.",
        "You always find a way to make simple things overly complicated. It's quite a talent.",
        "You're like a professional at avoiding responsibility. It's truly awe-inspiring.",
        "Your confidence knows no bounds... even when it's completely unfounded.",
        "You have an amazing talent for making everything about you. It's truly remarkable.",
        "You're the real MVP of missing deadlines. It's quite an accomplishment.",
        "Your ability to misunderstand even the clearest instructions is truly remarkable.",
        "You're a true expert at making mountains out of molehills. It's quite a talent.",
        "You have an incredible ability to make any situation about yourself. It's quite impressive.",
        "You're the reigning champion of underachievement. Congratulations on the impressive streak.",
        "Your fashion choices are always... interesting. It takes a special kind of person to pull off such looks.",
        "You're like a human tornado, leaving chaos in your wake wherever you go.",
        "Your ability to find problems where none exist is truly unparalleled.",
        "You have a real talent for making things unnecessarily complicated. It's quite a skill.",
        "You always manage to turn compliments into awkward moments. It's quite impressive.",
        "You really know how to make an impact... even if it's usually a negative one.",
        "Your ability to misunderstand even the most straightforward conversations is truly remarkable.",
        "You're a true artist when it comes to avoiding accountability.",
        "Your decision-making skills are truly one of a kind. And by that, I mean consistently terrible.",
        "You're like a walking, talking episode of a reality show. It's hard to look away.",
        "Your unique perspective on life is truly... something. I'm not quite sure what, though.",
        "You always find a way to make the simplest tasks seem like an uphill battle. It's quite a talent.",
        "You're so good at making excuses, you could write a book on it.",
        "You have a special talent for making even the best situations unbearable.",
        "Your work ethic is truly awe-inspiring... in its absence.",
        "You're like a detective, always finding the flaws in everything. It's quite impressive.",
        "Your ability to ignore instructions is truly remarkable.",
        "You're the reigning champion of turning molehills into mountains. Congratulations on the impressive streak.",
        "Your knack for complicating the simplest tasks is truly remarkable.",
        "You're like a magnet for drama. It's quite an impressive talent.",
        "Your ability to make everything about you is truly unmatched.",
        "You're a true master of turning compliments into insults. It's quite a skill.",
        "You have an uncanny ability to find problems where none exist. It's truly impressive.",
        "You really know how to make an entrance... and then promptly ruin the atmosphere.",
        "Your attention to detail is truly commendable... when it comes to finding faults in others.",
        "You're the undisputed champion of turning molehills into mountains. It's quite a talent.",
        "Your ability to make everything about yourself is truly unmatched.",
        "You're like a tornado, leaving chaos in your wake. It's quite a spectacle.",
        "You always manage to find a way to make simple tasks seem like an arduous journey. It's quite a talent.",
        "You're the Picasso of turning compliments into backhanded insults. It's truly remarkable.",
        "You have an incredible talent for finding problems where none exist. It's quite impressive.",
        "You really know how to make a lasting impression... unfortunately.",
        "Your ability to misunderstand even the most basic concepts is truly mind-boggling.",
        "You're like a professional at avoiding any form of responsibility. It's quite an achievement.",
        "Your decision-making skills are truly awe-inspiring... in their inconsistency.",
        "You always find a way to make everything about you. It's quite a talent.",
        "You're the MVP of turning easy tasks into complicated endeavors. Congratulations on the impressive streak.",
        "Your fashion choices are always... bold, to say the least. Not everyone can pull off such unique styles.",
        "You're like a walking, talking soap opera. Drama follows you everywhere.",
        "Your ability to find faults in everything is truly remarkable.",
        "You have a special talent for making simple things needlessly complex. It's quite a skill.",
        "You always manage to turn compliments into awkward encounters. It's quite impressive.",
        "You really know how to make an impact... in all the wrong ways.",
        "Your ability to misunderstand even the most straightforward conversations is truly astonishing.",
        "You're a true artist when it comes to evading responsibility.",
        "Your decision-making skills are truly one of a kind. And by that, I mean consistently poor.",
        "You're like a walking, talking reality show. It's hard to believe you're real sometimes.",
        "Your unique perspective on life never fails to leave me speechless. And not in a good way.",
        "You always find a way to make the simplest tasks seem like a Herculean effort. It's quite a talent.",
        "You're so good at making excuses, it's almost impressive.",
        "You have a special talent for making even the best situations unbearable.",
        "Your work ethic is truly awe-inspiring... in its absence.",
        "You're like a detective, always uncovering the flaws in everything. It's quite impressive.",
        "Your ability to ignore instructions is truly remarkable.",
        "You're the reigning champion of turning molehills into mountains. Congratulations on the impressive streak.",
        "Your knack for complicating the simplest tasks is truly remarkable.",
        "You're like a magnet for drama. It's quite an impressive talent.",
        "Your ability to make everything about you is truly unmatched.",
        "You're a true master of turning compliments into insults. It's quite a skill.",
        "You have an uncanny ability to find problems where none exist. It's truly impressive.",
        "You really know how to make an entrance... and then promptly ruin the atmosphere.",
        "Your attention to detail is truly commendable... when it comes to finding faults in others.",
        "You're the undisputed champion of turning molehills into mountains. It's quite a talent.",
        "Your ability to make everything about yourself is truly unmatched.",
        "You're like a tornado, leaving chaos in your wake. It's quite a spectacle.",
        "You always manage to find a way to make simple tasks seem like an arduous journey. It's quite a talent.",
        "You're the Picasso of turning compliments into backhanded insults. It's truly remarkable.",
        "You have an incredible talent for finding problems where none exist. It's quite impressive.",
        "You really know how to make a lasting impression... unfortunately.",
        "Your ability to misunderstand even the most basic concepts is truly mind-boggling.",
        "You're like a professional at avoiding any form of responsibility. It's quite an achievement.",
        "Your decision-making skills are truly awe-inspiring... in their inconsistency.",
        "You always find a way to make everything about you. It's quite a talent.",
        "You're the MVP of turning easy tasks into complicated endeavors. Congratulations on the impressive streak.",
        "Your fashion choices are always... bold, to say the least. Not everyone can pull off such unique styles.",
        "You're like a walking, talking soap opera. Drama follows you everywhere.",
        "Your ability to find faults in everything is truly remarkable.",
        "You have a special talent for making simple things needlessly complex. It's quite a skill.",
        "You always manage to turn compliments into awkward encounters. It's quite impressive.",
        "You really know how to make an impact... in all the wrong ways.",
        "Your ability to misunderstand even the most straightforward conversations is truly astonishing.",
        "You're a true artist when it comes to evading responsibility.",
        "Your decision-making skills are truly one of a kind. And by that, I mean consistently poor.",
        "You're like a walking, talking reality show. It's hard to believe you're real sometimes.",
        "Your unique perspective on life never fails to leave me speechless. And not in a good way.",
        "You always find a way to make the simplest tasks seem like a Herculean effort. It's quite a talent.",
        "You're so good at making excuses, it's almost impressive.",
        "You have a special talent for making even the best situations unbearable.",
        "Your work ethic is truly awe-inspiring... in its absence.",
        "You're like a detective, always uncovering the flaws in everything. It's quite impressive.",
        "Your ability to ignore instructions is truly remarkable.",
        "You're the reigning champion of turning molehills into mountains. Congratulations on the impressive streak.",
        "Your knack for complicating the simplest tasks is truly remarkable.",
        "You're like a magnet for drama. It's quite an impressive talent.",
        "Your ability to make everything about you is truly unmatched.",
        "You're a true master of turning compliments into insults. It's quite a skill.",
        "You have an uncanny ability to find problems where none exist. It's truly impressive.",
        "You really know how to make an entrance... and then promptly ruin the atmosphere.",
        "Your attention to detail is truly commendable... when it comes to finding faults in others.",
        "You're the undisputed champion of turning molehills into mountains. It's quite a talent.",
        "Your ability to make everything about yourself is truly unmatched.",
        "You're like a tornado, leaving chaos in your wake. It's quite a spectacle.",
        "You always manage to find a way to make simple tasks seem like an arduous journey. It's quite a talent.",
        "You're the Picasso of turning compliments into backhanded insults. It's truly remarkable.",
        "You have an incredible talent for finding problems where none exist. It's quite impressive.",
        "You really know how to make a lasting impression... unfortunately.",
        "Your ability to misunderstand even the most basic concepts is truly mind-boggling.",
        "You're like a professional at avoiding any form of responsibility. It's quite an achievement.",
        "Your decision-making skills are truly awe-inspiring... in their inconsistency.",
        "You always find a way to make everything about you. It's quite a talent.",
        "You're the MVP of turning easy tasks into complicated endeavors. Congratulations on the impressive streak.",
        "Your fashion choices are always... bold, to say the least. Not everyone can pull off such unique styles.",
        "You're like a walking, talking soap opera. Drama follows you everywhere.",
        "Your ability to find faults in everything is truly remarkable.",
        "You have a special talent for making simple things needlessly complex. It's quite a skill.",
        "You always manage to turn compliments into awkward encounters. It's quite impressive.",
        "You really know how to make an impact... in all the wrong ways.",
        "Your ability to misunderstand even the most straightforward conversations is truly astonishing.",
        "You're a true artist when it comes to evading responsibility.",
        "Your decision-making skills are truly one of a kind. And by that, I mean consistently poor.",
        "You're like a walking, talking reality show. It's hard to believe you're real sometimes.",
        "Your unique perspective on life never fails to leave me speechless. And not in a good way.",
        "You always find a way to make the simplest tasks seem like a Herculean effort. It's quite a talent.",
        "You're so good at making excuses, it's almost impressive.",
        "You have a special talent for making even the best situations unbearable.",
        "Your work ethic is truly awe-inspiring... in its absence.",
        "You're like a detective, always uncovering the flaws in everything. It's quite impressive.",
        "Your ability to ignore instructions is truly remarkable.",
        "You're the reigning champion of turning molehills into mountains. Congratulations on the impressive streak.",
        "Your knack for complicating the simplest tasks is truly remarkable.",
        "You're like a magnet for drama. It's quite an impressive talent.",
        "Your ability to make everything about you is truly unmatched.",
        "You're a true master of turning compliments into insults. It's quite a skill.",
        "You have an uncanny ability to find problems where none exist. It's truly impressive.",
        "You really know how to make an entrance... and then promptly ruin the atmosphere.",
        "Your attention to detail is truly commendable... when it comes to finding faults in others.",
        "You're the undisputed champion of turning molehills into mountains. It's quite a talent.",
        "Your ability to make everything about yourself is truly unmatched.",
        "You're like a tornado, leaving chaos in your wake. It's quite a spectacle.",
        "You always manage to find a way to make simple tasks seem like an arduous journey. It's quite a talent.",
        "You're the Picasso of turning compliments into backhanded insults. It's truly remarkable.",
        "You have an incredible talent for finding problems where none exist. It's quite impressive.",
        "You really know how to make a lasting impression... unfortunately.",
        "Your ability to misunderstand even the most basic concepts is truly mind-boggling.",
        "You're like a professional at avoiding any form of responsibility. It's quite an achievement.",
        "Your decision-making skills are truly awe-inspiring... in their inconsistency.",
        "You always find a way to make everything about you. It's quite a talent.",
        "You're the MVP of turning easy tasks into complicated endeavors. Congratulations on the impressive streak.",
        "Your fashion choices are always... bold, to say the least. Not everyone can pull off such unique styles.",
        "You're like a walking, talking soap opera. Drama follows you everywhere.",
        "Your ability to find faults in everything is truly remarkable.",
        "You have a special talent for making simple things needlessly complex. It's quite a skill.",
        "You always manage to turn compliments into awkward encounters. It's quite impressive.",
        "You really know how to make an impact... in all the wrong ways.",
        "Your ability to misunderstand even the most straightforward conversations is truly astonishing.",
        "You're a true artist when it comes to evading responsibility.",
        "Your decision-making skills are truly one of a kind. And by that, I mean consistently poor.",
        "You're like a walking, talking reality show. It's hard to believe you're real sometimes.",
        "Your unique perspective on life never fails to leave me speechless. And not in a good way.",
        "You always find a way to make the simplest tasks seem like a Herculean effort. It's quite a talent.",
        "You're so good at making excuses, it's almost impressive.",
        "You have a special talent for making even the best situations unbearable.",
        "Your work ethic is truly awe-inspiring... in its absence.",
        "You're like a detective, always uncovering the flaws in everything. It's quite impressive.",
        "Your ability to ignore instructions is truly remarkable.",
        "You're the reigning champion of turning molehills into mountains. Congratulations on the impressive streak.",
        "Your knack for complicating the simplest tasks is truly remarkable.",
        "You're like a magnet for drama. It's quite an impressive talent.",
        "Your ability to make everything about you is truly unmatched.",
        "You're a true master of turning compliments into insults. It's quite a skill.",
        "You have an uncanny ability to find problems where none exist. It's truly impressive.",
        "You really know how to make an entrance... and then promptly ruin the atmosphere.",
        "Your attention to detail is truly commendable... when it comes to finding faults in others.",
        "You're the undisputed champion of turning molehills into mountains. It's quite a talent.",
        "Your ability to make everything about yourself is truly unmatched.",
        "You're like a tornado, leaving chaos in your wake. It's quite a spectacle.",
        "You always manage to find a way to make simple tasks seem like an arduous journey. It's quite a talent.",
        "You're the Picasso of turning compliments into backhanded insults. It's truly remarkable.",
        "You have an incredible talent for finding problems where none exist. It's quite impressive.",
        "You really know how to make a lasting impression... unfortunately.",
        "Your ability to misunderstand even the most basic concepts is truly mind-boggling.",
        "You're like a professional at avoiding any form of responsibility. It's quite an achievement.",
        "Your decision-making skills are truly awe-inspiring... in their inconsistency.",
        "You always find a way to make everything about you. It's quite a talent.",
        "You're the MVP of turning easy tasks into complicated endeavors. Congratulations on the impressive streak.",
        "Your fashion choices are always... bold, to say the least. Not everyone can pull off such unique styles.",
        "You're like a walking, talking soap opera. Drama follows you everywhere.",
        "Your ability to find faults in everything is truly remarkable.",
        "You have a special talent for making simple things needlessly complex. It's quite a skill.",
        "You always manage to turn compliments into awkward encounters. It's quite impressive.",
        "You really know how to make an impact... in all the wrong ways.",
        "Your ability to misunderstand even the most straightforward conversations is truly astonishing.",
        "You're a true artist when it comes to evading responsibility.",
        "Your decision-making skills are truly one of a kind. And by that, I mean consistently poor.",
        "You're like a walking, talking reality show. It's hard to believe you're real sometimes.",
        "Your unique perspective on life never fails to leave me speechless. And not in a good way.",
        "You always find a way to make the simplest tasks seem like a Herculean effort. It's quite a talent.",
        "You're so good at making excuses, it's almost impressive.",
        "You have a special talent for making even the best situations unbearable.",
        "Your work ethic is truly awe-inspiring... in its absence.",
        "You're like a detective, always uncovering the flaws in everything. It's quite impressive.",
        "Your ability to ignore instructions is truly remarkable.",
        "You're the reigning champion of turning molehills into mountains. Congratulations on the impressive streak.",
        "Your knack for complicating the simplest tasks is truly remarkable.",
        "You're like a magnet for drama. It's quite an impressive talent.",
        "Your ability to make everything about you is truly unmatched.",
        "You're a true master of turning compliments into insults. It's quite a skill.",
        "You have an uncanny ability to find problems where none exist. It's truly impressive.",
        "You really know how to make an entrance... and then promptly ruin the atmosphere.",
        "Your attention to detail is truly commendable... when it comes to finding faults in others.",
        "You're the undisputed champion of turning molehills into mountains. It's quite a talent.",
        "Your ability to make everything about yourself is truly unmatched.",
        "You're like a tornado, leaving chaos in your wake. It's quite a spectacle.",
        "You always manage to find a way to make simple tasks seem like an arduous journey. It's quite a talent.",
        "You're the Picasso of turning compliments into backhanded insults. It's truly remarkable.",
        "You have an incredible talent for finding problems where none exist. It's quite impressive.",
        "You really know how to make a lasting impression... unfortunately.",
        "Your ability to misunderstand even the most basic concepts is truly mind-boggling.",
        "You're like a professional at avoiding any form of responsibility. It's quite an achievement.",
        "Your decision-making skills are truly awe-inspiring... in their inconsistency.",
        "You always find a way to make everything about you. It's quite a talent.",
        "You're the MVP of turning easy tasks into complicated endeavors. Congratulations on the impressive streak.",
        "Your fashion choices are always... bold, to say the least. Not everyone can pull off such unique styles.",
        "You're like a walking, talking soap opera. Drama follows you everywhere.",
        "Your ability to find faults in everything is truly remarkable.",
        "You have a special talent for making simple things needlessly complex. It's quite a skill.",
        "You always manage to turn compliments into awkward encounters. It's quite impressive.",
        "You really know how to make an impact... in all the wrong ways.",
        "Your ability to misunderstand even the most straightforward conversations is truly astonishing.",
        "You're a true artist when it comes to evading responsibility.",
        "Your decision-making skills are truly one of a kind. And by that, I mean consistently poor.",
        "You're like a walking, talking reality show. It's hard to believe you're real sometimes.",
        "Your unique perspective on life never fails to leave me speechless. And not in a good way.",
        "You always find a way to make the simplest tasks seem like a Herculean effort. It's quite a talent.",
        "You're so good at making excuses, it's almost impressive.",
        "You have a special talent for making even the best situations unbearable.",
        "Your work ethic is truly awe-inspiring... in its absence.",
        "You're like a detective, always uncovering the flaws in everything. It's quite impressive.",
        "Your ability to ignore instructions is truly remarkable.",
        "You're the reigning champion of turning molehills into mountains. Congratulations on the impressive streak.",
        "Your knack for complicating the simplest tasks is truly remarkable.",
        "You're like a magnet for drama. It's quite an impressive talent.",
        "Your ability to make everything about you is truly unmatched.",
        "You're a true master of turning compliments into insults. It's quite a skill.",
        "You have an uncanny ability to find problems where none exist. It's truly impressive.",
        "You really know how to make an entrance... and then promptly ruin the atmosphere.",
        "Your attention to detail is truly commendable... when it comes to finding faults in others.",
        "You're the undisputed champion of turning molehills into mountains. It's quite a talent.",
        "Your ability to make everything about yourself is truly unmatched.",
        "You're like a tornado, leaving chaos in your wake. It's quite a spectacle.",
        "You always manage to find a way to make simple tasks seem like an arduous journey. It's quite a talent.",
        "You're the Picasso of turning compliments into backhanded insults. It's truly remarkable.",
        "You have an incredible talent for finding problems where none exist. It's quite impressive.",
        "You really know how to make a lasting impression... unfortunately.",
        "Your ability to misunderstand even the most basic concepts is truly mind-boggling.",
        "You're like a professional at avoiding any form of responsibility. It's quite an achievement.",
        "Your decision-making skills are truly awe-inspiring... in their inconsistency.",
        "You always find a way to make everything about you. It's quite a talent.",
        "You're the MVP of turning easy tasks into complicated endeavors. Congratulations on the impressive streak.",
        "Your fashion choices are always... bold, to say the least. Not everyone can pull off such unique styles.",
        "You're like a walking, talking soap opera. Drama follows you everywhere.",
        "Your ability to find faults in everything is truly remarkable.",
        "You have a special talent for making simple things needlessly complex. It's quite a skill.",
        "You always manage to turn compliments into awkward encounters. It's quite impressive.",
        "You really know how to make an impact... in all the wrong ways.",
        "Your ability to misunderstand even the most straightforward conversations is truly astonishing.",
        "You're a true artist when it comes to evading responsibility.",
        "Your decision-making skills are truly one of a kind. And by that, I mean consistently poor.",
        "You're like a walking, talking reality show. It's hard to believe you're real sometimes.",
        "Your unique perspective on life never fails to leave me speechless. And not in a good way.",
        "You always find a way to make the simplest tasks seem like a Herculean effort. It's quite a talent.",
        "You're so good at making excuses, it's almost impressive.",
        "You have a special talent for making even the best situations unbearable.",
        "Your work ethic is truly awe-inspiring... in its absence.",
        "You're like a detective, always uncovering the flaws in everything. It's quite impressive.",
        "Your ability to ignore instructions is truly remarkable.",
        "You're the reigning champion of turning molehills into mountains. Congratulations on the impressive streak.",
        "Your knack for complicating the simplest tasks is truly remarkable.",
        "You're like a magnet for drama. It's quite an impressive talent.",
        "Your ability to make everything about you is truly unmatched.",
        "You're a true master of turning compliments into insults. It's quite a skill.",
        "You have an uncanny ability to find problems where none exist. It's truly impressive.",
        "You really know how to make an entrance... and then promptly ruin the atmosphere.",
        "Your attention to detail is truly commendable... when it comes to finding faults in others.",
        "You're the undisputed champion of turning molehills into mountains. It's quite a talent.",
        "Your ability to make everything about yourself is truly unmatched.",
        "You're like a tornado, leaving chaos in your wake. It's quite a spectacle.",
        "You always manage to find a way to make simple tasks seem like an arduous journey. It's quite a talent.",
        "You're the Picasso of turning compliments into backhanded insults. It's truly remarkable.",
        "You have an incredible talent for finding problems where none exist. It's quite impressive.",
        "You really know how to make a lasting impression... unfortunately.",
        "Your ability to misunderstand even the most basic concepts is truly mind-boggling.",
        "You're like a professional at avoiding any form of responsibility. It's quite an achievement.",
        "Your decision-making skills are truly awe-inspiring... in their inconsistency.",
        "You always find a way to make everything about you. It's quite a talent.",
        "You're the MVP of turning easy tasks into complicated endeavors. Congratulations on the impressive streak.",
        "Your fashion choices are always... bold, to say the least. Not everyone can pull off such unique styles.",
        "You're like a walking, talking soap opera. Drama follows you everywhere.",
        "Your ability to find faults in everything is truly remarkable.",
        "You have a special talent for making simple things needlessly complex. It's quite a skill.",
        "You always manage to turn compliments into awkward encounters. It's quite impressive.",
        "You really know how to make an impact... in all the wrong ways.",
        "Your ability to misunderstand even the most straightforward conversations is truly astonishing.",
        "You're a true artist when it comes to evading responsibility.",
        "Your decision-making skills are truly one of a kind. And by that, I mean consistently poor.",
        "You're like a walking, talking reality show. It's hard to believe you're real sometimes.",
        "Your unique perspective on life never fails to leave me speechless. And not in a good way.",
        "You always find a way to make the simplest tasks seem like a Herculean effort. It's quite a talent.",
        "You're so good at making excuses, it's almost impressive.",
        "You have a special talent for making even the best situations unbearable.",
        "Your work ethic is truly awe-inspiring... in its absence.",
        "You're like a detective, always uncovering the flaws in everything. It's quite impressive.",
        "Your ability to ignore instructions is truly remarkable.",
        "You're the reigning champion of turning molehills into mountains. Congratulations on the impressive streak.",
        "Your knack for complicating the simplest tasks is truly remarkable.",
        "You're like a magnet for drama. It's quite an impressive talent.",
        "Your ability to make everything about you is truly unmatched.",
        "You're a true master of turning compliments into insults. It's quite a skill.",
        "You have an uncanny ability to find problems where none exist. It's truly impressive.",
        "You really know how to make an entrance... and then promptly ruin the atmosphere.",
        "Your attention to detail is truly commendable... when it comes to finding faults in others.",
        "You're the undisputed champion of turning molehills into mountains. It's quite a talent.",
        "Your ability to make everything about yourself is truly unmatched.",
        "You're like a tornado, leaving chaos in your wake. It's quite a spectacle.",
        "You always manage to find a way to make simple tasks seem like an arduous journey. It's quite a talent.",
        "You're the Picasso of turning compliments into backhanded insults. It's truly remarkable.",
        "You have an incredible talent for finding problems where none exist. It's quite impressive.",
        "You really know how to make a lasting impression... unfortunately.",
        "Your ability to misunderstand even the most basic concepts is truly mind-boggling.",
        "You're like a professional at avoiding any form of responsibility. It's quite an achievement.",
        "Your decision-making skills are truly awe-inspiring... in their inconsistency.",
        "You always find a way to make everything about you. It's quite a talent.",
        "You're the MVP of turning easy tasks into complicated endeavors. Congratulations on the impressive streak.",
        "Your fashion choices are always... bold, to say the least. Not everyone can pull off such unique styles.",
        "You're like a walking, talking soap opera. Drama follows you everywhere.",
        "Your ability to find faults in everything is truly remarkable.",
        "You have a special talent for making simple things needlessly complex. It's quite a skill.",
        "You always manage to turn compliments into awkward encounters. It's quite impressive.",
        "You really know how to make an impact... in all the wrong ways.",
        "Your ability to misunderstand even the most straightforward conversations is truly astonishing.",
        "You're a true artist when it comes to evading responsibility.",
        "Your decision-making skills are truly one of a kind. And by that, I mean consistently poor.",
        "You're like a walking, talking reality show. It's hard to believe you're real sometimes.",
        "Your unique perspective on life never fails to leave me speechless. And not in a good way.",
        "You always find a way to make the simplest tasks seem like a Herculean effort. It's quite a talent.",
        "You're so good at making excuses, it's almost impressive.",
        "You have a special talent for making even the best situations unbearable.",
        "Your work ethic is truly awe-inspiring... in its absence.",
        "You're like a detective, always uncovering the flaws in everything. It's quite impressive.",
        "Your ability to ignore instructions is truly remarkable.",
        "You're the reigning champion of turning molehills into mountains. Congratulations on the impressive streak.",
        "Your knack for complicating the simplest tasks is truly remarkable.",
        "You're like a magnet for drama. It's quite an impressive talent.",
        "Your ability to make everything about you is truly unmatched.",
        "You're a true master of turning compliments into insults. It's quite a skill.",
        "You have an uncanny ability to find problems where none exist. It's truly impressive.",
        "You really know how to make an entrance... and then promptly ruin the atmosphere.",
        "Your attention to detail is truly commendable... when it comes to finding faults in others.",
        "You're the undisputed champion of turning molehills into mountains. It's quite a talent.",
        "Your ability to make everything about yourself is truly unmatched.",
        "You're like a tornado, leaving chaos in your wake. It's quite a spectacle.",
        "You always manage to find a way to make simple tasks seem like an arduous journey. It's quite a talent.",
        "You're the Picasso of turning compliments into backhanded insults. It's truly remarkable.",
        "You have an incredible talent for finding problems where none exist. It's quite impressive.",
        "You really know how to make a lasting impression... unfortunately.",
        "Your ability to misunderstand even the most basic concepts is truly mind-boggling.",
        "You're like a professional at avoiding any form of responsibility. It's quite an achievement.",
        "Your decision-making skills are truly awe-inspiring... in their inconsistency.",
        "You always find a way to make everything about you. It's quite a talent.",
        "You're the MVP of turning easy tasks into complicated endeavors. Congratulations on the impressive streak.",
        "Your fashion choices are always... bold, to say the least. Not everyone can pull off such unique styles.",
        "You're like a walking, talking soap opera. Drama follows you everywhere.",
        "Your ability to find faults in everything is truly remarkable.",
        "You have a special talent for making simple things needlessly complex. It's quite a skill.",
        "You always manage to turn compliments into awkward encounters. It's quite impressive.",
        "You really know how to make an impact... in all the wrong ways.",
        "Your ability to misunderstand even the most straightforward conversations is truly astonishing.",
        "You're a true artist when it comes to evading responsibility.",
        "Your decision-making skills are truly one of a kind. And by that, I mean consistently poor.",
        "You're like a walking, talking reality show. It's hard to believe you're real sometimes.",
        "Your unique perspective on life never fails to leave me speechless. And not in a good way.",
        "You always find a way to make the simplest tasks seem like a Herculean effort. It's quite a talent.",
        "You're so good at making excuses, it's almost impressive.",
        "You have a special talent for making even the best situations unbearable.",
        "Your work ethic is truly awe-inspiring... in its absence.",
        "You're like a detective, always uncovering the flaws in everything. It's quite impressive.",
        "Your ability to ignore instructions is truly remarkable.",
        "You're the reigning champion of turning molehills into mountains. Congratulations on the impressive streak.",
        "Your knack for complicating the simplest tasks is truly remarkable.",
        "You're like a magnet for drama. It's quite an impressive talent.",
        "Your ability to make everything about you is truly unmatched.",
        "You're a true master of turning compliments into insults. It's quite a skill.",
        "You have an uncanny ability to find problems where none exist. It's truly impressive.",
        "You really know how to make an entrance... and then promptly ruin the atmosphere.",
        "Your attention to detail is truly commendable... when it comes to finding faults in others.",
        "You're the undisputed champion of turning molehills into mountains. It's quite a talent.",
        "Your ability to make everything about yourself is truly unmatched.",
        "You're like a tornado, leaving chaos in your wake. It's quite a spectacle.",
        "You always manage to find a way to make simple tasks seem like an arduous journey. It's quite a talent.",
        "You're the Picasso of turning compliments into backhanded insults. It's truly remarkable.",
        "You have an incredible talent for finding problems where none exist. It's quite impressive.",
        "You really know how to make a lasting impression... unfortunately.",
        "Your ability to misunderstand even the most basic concepts is truly mind-boggling.",
        "You're like a professional at avoiding any form of responsibility. It's quite an achievement.",
        "Your decision-making skills are truly awe-inspiring... in their inconsistency.",
        "You always find a way to make everything about you. It's quite a talent.",
        "You're the MVP of turning easy tasks into complicated endeavors. Congratulations on the impressive streak.",
        "Your fashion choices are always... bold, to say the least. Not everyone can pull off such unique styles.",
        "You're like a walking, talking soap opera. Drama follows you everywhere.",
        "Your ability to find faults in everything is truly remarkable.",
        "You have a special talent for making simple things needlessly complex. It's quite a skill.",
        "You always manage to turn compliments into awkward encounters. It's quite impressive.",
        "You really know how to make an impact... in all the wrong ways.",
        "Your ability to misunderstand even the most straightforward conversations is truly astonishing.",
        "You're a true artist when it comes to evading responsibility.",
        "Your decision-making skills are truly one of a kind. And by that, I mean consistently poor.",
        "You're like a walking, talking reality show. It's hard to believe you're real sometimes.",
        "Your unique perspective on life never fails to leave me speechless. And not in a good way.",
        "You always find a way to make the simplest tasks seem like a Herculean effort. It's quite a talent.",
        "You're so good at making excuses, it's almost impressive."
    ]
    
    return random.choice(excuses)

def generate_excuse_button():
    excuse_label.configure(text=generate_excuse())

# Create the main application window
app = tk.Tk()
app.title("Aggressive Compliment Giver")

# Set the window attributes to fullscreen
app.attributes("-fullscreen", True)

# Create a frame for the content
content_frame = ttk.Frame(app, padding=(20, 40))
content_frame.pack(expand=True)

# Create a label to display the generated excuse
excuse_label = ttk.Label(content_frame, text="", wraplength=int(app.winfo_screenwidth() * 0.75), font=("Helvetica", 15))
excuse_label.pack(pady=20)

# Create a button to generate a new excuse
generate_button = ttk.Button(content_frame, text="Generate Compliment", command=generate_excuse_button)
generate_button.pack()

# Start the application
app.mainloop()
