import random
import tkinter as tk
from tkinter import ttk
from tkinter import messagebox

def generate_excuse():
    excuses = [
        "My dog ate my homework.",
        "I accidentally joined a circus and couldn't make it.",
        "I got trapped in an elevator with a clown.",
        "My time machine malfunctioned and I got stuck in the 18th century.",
        "Aliens abducted me and erased my memory.",
        "I was on a top-secret mission to save the world from a squirrel invasion.",
        "A swarm of bees followed me and I had to take a detour.",
        "My cat unplugged my alarm clock.",
        "I fell into a deep rabbit hole while chasing the White Rabbit.",
        "I accidentally turned myself invisible and couldn't find my way back.",
        "I was trapped in a parallel universe with talking dinosaurs.",
        "I was held hostage by a group of rogue garden gnomes.",
        "My psychic told me not to leave the house today.",
        "I got caught in a dance-off with a street performer.",
        "I was on a quest to find the Holy Grail.",
        "My refrigerator ate all my food, and I had to defend it.",
        "I was abducted by pirates and forced to walk the plank.",
        "I was participating in a hot dog eating contest and lost track of time.",
        "I was stuck in a revolving door for hours.",
        "My computer became sentient and refused to let me leave.",
        "I accidentally shrunk myself and got stuck in a shoe.",
        "A rogue squirrel stole my car keys.",
        "I got caught in a time loop and kept reliving the same day.",
        "I was mistaken for a celebrity and had to sign autographs.",
        "A swarm of ladybugs invaded my house and I had to deal with them.",
        "I was chosen as a secret agent and had to go undercover.",
        "I was teleported to a parallel universe where time moves backwards.",
        "I had a sudden urge to learn how to juggle flaming torches.",
        "I was trapped inside a video game and couldn't escape.",
        "My alarm clock only spoke to me in Mandarin Chinese.",
        "I became entangled in a kite string and couldn't get free.",
        "I fell into a deep sleep and had a dream that I was a chicken.",
        "I was busy perfecting my teleportation device.",
        "I was trapped inside a vending machine trying to get a free snack.",
        "I discovered a hidden treasure map and had to follow its clues.",
        "I was recruited by a secret society of magicians.",
        "I was busy teaching my goldfish how to play the piano.",
        "I accidentally joined a mariachi band and had to perform at a wedding.",
        "I was abducted by aliens who wanted to learn human dance moves.",
        "I was trapped in a giant bubble and couldn't find the exit.",
        "I was attending a conference on how to properly wear mismatched socks.",
        "I was having a heated debate with a statue and lost track of time.",
        "My car tires were stolen, so I had to walk to work on stilts.",
        "I was asked to participate in a scientific experiment to communicate with plants.",
        "I got stuck in a revolving door and became an unwitting attraction.",
        "I was busy practicing my pirate impersonation for Talk Like a Pirate Day.",
        "I was challenged to a thumb wrestling championship and couldn't back down.",
        "I was trying to break the world record for the most bubblegum bubbles blown at once.",
        "I accidentally joined a group of synchronized swimmers and had to learn the routine.",
        "I was trapped inside a giant bubblegum bubble and had to wait for it to pop.",
        "I accidentally joined a synchronized swimming team and couldn't miss practice.",
        "I was trapped inside a fortune cookie factory and had to find my way out.",
        "I got lost in a maze of my own thoughts.",
        "A flock of seagulls stole my shoes and I had to chase them down.",
        "I was trapped inside a vending machine and had to eat my way out.",
        "I became a superhero overnight and had to save the city from paper cuts.",
        "I was recruited by a group of time-traveling hamsters to solve a cheese-related mystery.",
        "I had to attend a top-secret meeting with the tooth fairy.",
        "I accidentally joined a group of penguins and had to learn their marching routine.",
        "I was caught in a battle between unicorns and dragons.",
        "I got trapped in a revolving door with a mime artist.",
        "I was challenged to a thumb war tournament and couldn't back down.",
        "I was abducted by aliens who needed help deciphering human fashion trends.",
        "I accidentally turned myself into a balloon and couldn't find a pin to pop myself.",
        "I was invited to a squirrel wedding and couldn't refuse.",
        "I got caught in a spider web and had to negotiate my way out with the spider.",
        "I was trapped inside a giant bubble and had to wait for it to burst.",
        "I had to test the durability of bubble wrap for a science experiment.",
        "I was asked to participate in a dance-off with a group of penguins.",
        "I was busy perfecting my skills as a professional napper.",
        "I got stuck in a tree trying to save a stranded cat.",
        "I was chosen as a judge for a snail racing competition.",
        "I accidentally joined a group of circus performers and had to learn the tightrope.",
        "I was trapped inside a giant piñata and had to wait for someone to break it open.",
        "I had to attend a marathon for turtles and cheer them on.",
        "I was on a secret mission to find the world's largest rubber duck.",
        "I was trapped inside a giant bubble bath and had to find a way to drain it.",
        "I accidentally joined a choir of frogs and had to learn their songs.",
        "I was participating in a squirrel Olympics and won a gold acorn.",
        "I got stuck in a giant game of Jenga and had to carefully remove each block.",
        "I had to attend a seminar on how to properly wear socks with sandals.",
        "I was challenged to a staring contest with a statue and couldn't blink.",
        "I was busy practicing my pogo stick skills for a world record attempt.",
        "I accidentally joined a group of skydivers and had to jump out of a plane.",
        "I was trapped inside a giant puzzle and had to solve it piece by piece.",
        "I had to attend a snail fashion show and judge the best-dressed snail.",
        "I got caught in a web of conspiracy theories and had to unravel the truth.",
        "I was busy training a team of squirrels for the World Cup of Nut Gathering.",
        "I accidentally joined a group of circus clowns and had to learn how to juggle.",
        "I was trapped inside a giant bubblegum bubble and had to wait for it to deflate.",
        "I had to participate in a magic show and learn how to pull rabbits out of hats.",
        "I was on a quest to find the legendary lost sock that always disappears in the dryer.",
        "I accidentally joined a group of pogo stick enthusiasts and had to master the art.",
        "I was trapped inside a giant game of Twister and had to contort my way out.",
        "I had to attend a conference on the art of balancing spoons on your nose.",
        "I got lost in a hall of mirrors and couldn't find my way out.",
        "I was challenged to a game of hide-and-seek with a chameleon and couldn't find it.",
        "I accidentally joined a group of hula hoop performers and had to learn their routine.",
        "I was trapped inside a giant snow globe and had to wait for the snow to settle.",
        "I had to attend a seminar on the proper technique for eating spaghetti without utensils.",
        "I got caught in a dance-off with a group of penguins and couldn't stop dancing.",
        "I was busy training my goldfish to perform synchronized swimming routines.",
        "I accidentally joined a group of skateboarders and had to learn how to do tricks.",
        "I was trapped inside a giant bubble wrap and had to pop my way out.",
        "I had to attend a convention for people who collect rubber ducks.",
        "I got stuck in a giant game of hopscotch and had to complete each square.",
        "I was challenged to a game of tag with a cheetah and couldn't outrun it.",
        "I accidentally joined a group of jugglers and had to learn how to juggle flaming torches.",
        "I was trapped inside a giant slinky and had to walk down the stairs.",
        "I had to attend a conference on the proper way to wear a hat with a propeller.",
        "I got caught in a game of Simon Says and couldn't stop following the instructions.",
        "I was busy training a team of ants for the Olympics of Ant Hill Digging.",
        "I accidentally joined a group of tightrope walkers and had to learn how to balance.",
        "I was trapped inside a giant game of Rock-Paper-Scissors and had to play against myself.",
        "I had to attend a seminar on the art of painting with spaghetti noodles.",
        "I got stuck in a giant game of chess and had to strategize my way out.",
        "I was challenged to a staring contest with a cat and couldn't look away.",
        "I accidentally joined a group of fire breathers and had to learn the technique.",
        "I was trapped inside a giant piñata and had to wait for someone to break it open.",
        "I had to attend a conference on the proper technique for eating spaghetti without utensils.",
        "I got stuck in a giant game of hopscotch and had to complete each square.",
        "I was challenged to a game of tag with a cheetah and couldn't outrun it.",
        "I accidentally joined a group of jugglers and had to learn how to juggle flaming torches.",
        "I was trapped inside a giant slinky and had to walk down the stairs.",
        "I had to attend a conference on the proper way to wear a hat with a propeller.",
        "I got caught in a game of Simon Says and couldn't stop following the instructions.",
        "I was busy training a team of ants for the Olympics of Ant Hill Digging.",
        "I accidentally joined a group of tightrope walkers and had to learn how to balance.",
        "I was trapped inside a giant game of Rock-Paper-Scissors and had to play against myself.",
        "I had to attend a seminar on the art of painting with spaghetti noodles.",
        "I got stuck in a giant game of chess and had to strategize my way out.",
        "I was challenged to a staring contest with a cat and couldn't look away.",
        "I accidentally joined a group of fire breathers and had to learn the technique.",
        "I was trapped inside a giant bubble and had to find a way to pop it.",
        "I had to attend a conference on the art of juggling rubber ducks.",
        "I got caught in a game of tug-of-war with a group of squirrels and couldn't let go.",
        "I accidentally joined a group of magicians and had to learn how to perform tricks.",
        "I was trapped inside a giant bubble wrap and had to pop my way out.",
        "I had to participate in a pancake flipping contest and couldn't miss it.",
        "I was on a secret mission to find the world's largest rubber band ball.",
        "I accidentally joined a group of breakdancers and had to learn their moves.",
        "I was trapped inside a giant maze and had to find my way to the exit.",
        "I had to attend a conference on the art of balancing spoons on your nose.",
        "I got caught in a game of freeze tag and couldn't unfreeze myself.",
        "I accidentally joined a group of trapeze artists and had to learn how to swing.",
        "I was trapped inside a giant game of Tic Tac Toe and had to strategize my way out.",
        "I had to attend a seminar on the proper way to eat pizza with chopsticks.",
        "I got stuck in a giant game of Connect Four and had to find a way to win.",
        "I was challenged to a game of hide-and-seek with a chameleon and couldn't find it.",
        "I accidentally joined a group of acrobats and had to learn their routines.",
        "I was trapped inside a giant bubble and had to wait for it to pop.",
        "I had to participate in a hula hoop competition and couldn't miss it.",
        "I was on a secret mission to find the world's largest rubber duck.",
        "I accidentally joined a group of breakdancers and had to learn their moves.",
        "I was trapped inside a giant maze and had to find my way to the exit.",
        "I had to attend a conference on the art of balancing spoons on your nose.",
        "I got caught in a game of freeze tag and couldn't unfreeze myself.",
        "I accidentally joined a group of trapeze artists and had to learn how to swing.",
        "I was trapped inside a giant game of Tic Tac Toe and had to strategize my way out.",
        "I had to attend a seminar on the proper way to eat pizza with chopsticks.",
        "I got stuck in a giant game of Connect Four and had to find a way to win.",
        "I was challenged to a game of hide-and-seek with a chameleon and couldn't find it.",
        "I accidentally joined a group of acrobats and had to learn their routines.",
        "I was trapped inside a giant bubble and had to wait for it to pop.",
        "I had to participate in a hula hoop competition and couldn't miss it.",
        "I was on a secret mission to find the world's largest rubber duck.",
        "I accidentally joined a group of breakdancers and had to learn their moves.",
        "I was trapped inside a giant maze and had to find my way to the exit.",
        "I had to attend a conference on the art of balancing spoons on your nose.",
        "I got caught in a game of freeze tag and couldn't unfreeze myself.",
        "I accidentally joined a group of trapeze artists and had to learn how to swing.",
        "I was trapped inside a giant game of Tic Tac Toe and had to strategize my way out.",
        "I had to attend a seminar on the proper way to eat pizza with chopsticks.",
        "I got stuck in a giant game of Connect Four and had to find a way to win.",
        "I was challenged to a game of hide-and-seek with a chameleon and couldn't find it.",
        "I accidentally joined a group of acrobats and had to learn their routines.",
        "I was trapped inside a giant bubble and had to wait for it to pop.",
        "I had to participate in a hula hoop competition and couldn't miss it."
    ]
    
    return random.choice(excuses)

def generate_excuse_button():
    excuse_label.configure(text=generate_excuse())

# Create the main application window
app = tk.Tk()
app.title("Random Excuse Generator")

# Set the window attributes to fullscreen
app.attributes("-fullscreen", True)

# Create a frame for the content
content_frame = ttk.Frame(app, padding=(20, 40))
content_frame.pack(expand=True)

# Create a label to display the generated excuse
excuse_label = ttk.Label(content_frame, text="", wraplength=int(app.winfo_screenwidth() * 0.75), font=("Helvetica", 15))
excuse_label.pack(pady=20)

# Create a button to generate a new excuse
generate_button = ttk.Button(content_frame, text="Generate Excuse", command=generate_excuse_button)
generate_button.pack()

# Start the application
app.mainloop()
